### PR TITLE
fix(YouTube/Hide feed components): `Hide Latest videos button` setting does not support tablets

### PR DESCRIPTION
**Pull request by YT-Advanced**
The `Tap to update` button in Youtube is similar with the button in https://github.com/inotia00/ReVanced_Extended/issues/1880.

Since the `Tap to update` and `Latest video` button have the same function, I think splitting into a new setting is unnecessary

### CODE REVIEW

**Comment by YT-Advanced** [comment]
@inotia00 `Latest video button` method structure is similar with `Tap to update button` method. So we can use fingerprint as below to resolve both.
But I don't seem to have any idea to do this. Do you have any suggestion ?

```kotlin
package app.revanced.patches.youtube.feed.components.fingerprints

import app.revanced.patcher.fingerprint.MethodFingerprint
import com.android.tools.smali.dexlib2.Opcode

internal object ContentPillFingerprint : MethodFingerprint(
    returnType = "V",
    opcodes = listOf(
        Opcode.CONST,
        Opcode.IGET_OBJECT,
        Opcode.INVOKE_VIRTUAL,
        Opcode.MOVE_RESULT_OBJECT
    ),
    strings = listOf("Controller must be initialized for a feed before the content pill can be shown.")
)
```

**Comment by inotia00** [comment]
The reason why the structure of the two methods is similar is probably because both classes inherit from one parent class

The structure of the methods is the same, but the View Id is different, so both classes need to be patched

**Comment by inotia00** [comment]
This PR fixes issue https://github.com/inotia00/ReVanced_Extended/issues/1596, so the title of the PR has been changed

**Comment by inotia00** [comment]
Thanks

**Pull request merged**
