### PR TITLE
Changes to close #1407 and #1529

### LINKED ISSUE #1407: suggestion: some patch names and settings are not properly labeled
### Application

YouTube

### Description

Correct these strings to match ReVanced Extended just by adding "Extended" after "ReVanced":
Import ReVanced settings from file or export ReVanced settings to file;
Save your ReVanced settings to file;
Fetch ReVanced settings from saved file;
Your SponsorBlock JSON configuration that can be imported/exported to ReVanced and other SponsorBlock platforms. This includes your private user id. Be sure to share this wisely

P.S. i forgot to say about patch descriptions, but they need changes too
YT:
`microg-support`	Allows ReVanced to run without root and under a different package name with MicroG.;
`settings`	Applies mandatory patches to implement ReVanced settings into the application.

YTM:
`microg-support`	Allows ReVanced Music to run without root and under a different package name with MicroG.;
`settings`	Adds settings for ReVanced to YouTube Music.

Reddit:
`reddit-settings` Adds ReVanced settings to Reddit.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

### PR DESCRIPTION
**Pull request by girshcatt**
Changes to close https://github.com/inotia00/ReVanced_Extended/issues/1407 and https://github.com/inotia00/ReVanced_Extended/issues/1529
Also I made little improvements to some strings to look like in YTM, i mean: Spoofing the client version to the old version

• This will change the appearance of the app, but unknown side effects may occur
• If later turned off, the old UI may remain until clear the app data

How it was in YT: Spoofing the client version to the old version

This will change the appearance of the app, but unknown side effects may occur
If later turned off, the old UI may remain until clear the app data

### CODE REVIEW

**Comment by kazimmt** [comment]
Just because you're adding a single . (dot)
People needs to translate them all again.

**Comment by girshcatt** [comment]
> Just because you're adding a single . (dot) People needs to translate them all again.

Oh sorry, for this pr i prepared only three commits, other commits only for me, can you help me how i can leave only three commits in pr?

**Comment by girshcatt** [comment]
I wanted to create then a separate pr to close dot issue

**Comment by girshcatt** [comment]
But i dont know how to leave only some commits in pr, not all changes i did

**Comment by girshcatt** [comment]
Better just ignore this pr this time, better if today i will be done with dots problem, edit issue and just leave it to inotia

**Comment by girshcatt** [comment]
@kazimmt About this, i know, but this is not 100% like you said, translations in crowdin marked like approved previously just remove approval, but all the same translations go in project. They not need smt to change, only if translators want, they can add dots. At this moment i work with dots in YT settings

**Comment by inotia00** [comment]
`README.md` and `patches.json` files do not need to be modified
These files will be overwritten during the build process

**Comment by girshcatt** [comment]
Oh, i think my problem that i opened pr eqrlier than i started to work with https://github.com/inotia00/ReVanced_Extended/issues/1529 Soon as i will be ready i will open pr to close 1529 issue YouTube part

**Pull request merged**
