### PR TITLE
fix(Custom branding name): patching time is too long

### LINKED ISSUE #1887: bug(YouTube/Custom branding name YouTube): Patching time is long on RVX Manager
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

Patching speed of `Custom branding name YouTube` is slow on RVX Manager.
After https://github.com/inotia00/revanced-patches/commit/441a9ecd586ca0bf6f372e38d43d9c6ae57aa230, the speed is certainly improved significantly, but it still takes time.

I measured the patching time on a mid-range device (Snapdragon 662, 4GB RAM).

Result:
- `AbstractRemoveStringsElementsPatch` took 40366 ms
- `CustomBrandingNamePatch` took 63 ms

Therefore, it seems that `AbstractRemoveStringsElementsPatch` takes long time to remove "application_name" string from each language files. (40 seconds)

### Error logs

_No response_

### Solution

Match to official ReVanced code.
Official ReVanced uses a strategy of writing the new app name directly in AndroidManifest.xml.
https://github.com/ReVanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/layout/branding/CustomBrandingPatch.kt#L101
It takes only 3ms on the same environment.

### Effect of matching official revanced code

In case you are concerned about the impact, I have done some research in advance.

`@string/application_name` is used in these files:

```
res/layout/action_bar_ringo.xml
res/layout/action_bar_ringo_background.xml
res/layout/action_bar_ringo_background.xml
res/layout/action_bar_ringo_background_static.xml
smali_classes4/gcm.smali
smali_classes4/jqb.smali
smali_classes4/ltt.smali (As of 18.45.43)
```

For general users, this will affect the title text that appears in the ActionBar of WatchWhileActivity before the YouTube logo image loads, but it probably isn't a big deal. (It only appears for a short time on first startup)

action_bar

### Device Environment

Android 11, Snapdragon 662, 4GB RAM, RVX Manager 1.18.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

### PR DESCRIPTION
**Pull request by inotia00**
Original: Remove the Elements through the regex, then add a new element.
PR: Find all the labels included in all `strings.xml` via `getElementsByTagName` and change the value.

Closes https://github.com/inotia00/ReVanced_Extended/issues/1887

### CODE REVIEW

**Comment by inotia00** [comment]
@kitadai31, can you test how much patch time is reduced through this PR?

**Comment by kitadai31** [comment]
It's worse than now
It took 2m:30s (sd662, 4GB RAM)

The speed is back to before 441a9ec

**Comment by inotia00** [comment]
I didn't notice because I didn't measure the exact time, but thank you
I will close this PR and apply the way you left in the comment https://github.com/inotia00/ReVanced_Extended/issues/1887#issuecomment-1888710969

**Comment by kitadai31** [comment]
OK, thank you.

**Pull request closed without merging**
