### PR TITLE
feat(YouTube/Overlay buttons): add `Collapse` button and update thin-type overlay button icons

### PR DESCRIPTION
**Pull request by MondayNitro**
corrected sizes of unevenly sized icons and thickened icons for low res(xhdpi) since they look light/blur

### CODE REVIEW

**Comment by federicogith** [comment]
@MondayNitro can you add `Bold`, `Rounded` and `Thin` icons for the `Collapse` button?

**Comment by federicogith** [comment]
@MondayNitro can you add `Bold`, `Rounded` and `Thin` icons for the `Collapse` button?
352765711-29a5843e-ba50-44ab-b3d1-d8aa5f3a8aa4

**Comment by MondayNitro** [comment]
> @MondayNitro can you add `Bold`, `Rounded` and `Thin` icons for the `Collapse` button?

i forgot about it since i keep collapse button hidden

**Comment by MondayNitro** [comment]
Screenshot_20240816-183413_YouTube

**Comment by inotia00** [comment]
Thanks

**Pull request merged**
