### PR TITLE
fix: remove chimera reference and disable advertising id

### PR DESCRIPTION
**Pull request by 0xrxL**
Patching this reference can cause multiple log spamming of "not found error" (I guess a specific data is lack on MicroG).

### CODE REVIEW

**Comment by 0xrxL** [comment]
P.S: If you are interested, there is a new patch on uDrop to disable advertising id getter method and prevent another log error (it's a runnable, so should be good for battery).

**Comment by inotia00** [comment]
It seems that the latest uDrop has reverted the change to CastDynamiteModule
("com.google.android.gms.cast.framework.internal.CastDynamiteModuleImpl", "Failed to load module via V2: ")

Should I revert it?

**Comment by 0xrxL** [comment]
> It seems that the latest uDrop has reverted the change to CastDynamiteModule ("com.google.android.gms.cast.framework.internal.CastDynamiteModuleImpl", "Failed to load module via V2: ")
> 
> Should I revert it?

Yeah...Try to check if battery consuption improves by reverting them.

**Comment by inotia00** [comment]
I'm sorry for the late review, I was so busy
Thank you for your contribution

**Comment by 0xrxL** [comment]
> I'm sorry for the late review, I was so busy Thank you for your contribution

Give also a look at Live_Chat_Elements_Removal on uDrop, there are some useful patches to cleanup live chat panel.

**Pull request merged**
