### PR TITLE
feat(whitelist): Bring back whitelist feature

### PR DESCRIPTION
**Pull request by YT-Advanced**
Integrations changes: https://github.com/inotia00/revanced-integrations/pull/15

### CODE REVIEW

**Comment by YT-Advanced** [comment]
Now it is ready to merge

**Comment by YT-Advanced** [comment]
@inotia00 Should we add a guide for helping user create their own key ?

**Comment by inotia00** [comment]
I will not merge this

RVX will be discontinued after rollout final release in next week, so if an issue with `whitelist` patch is found, nobody can't fix it

so.. It is recommended to fork and introduce it to people after RVX is discontinued

**Comment by inotia00** [comment]
Instead, if you add me as a collaborator in your repo, I can give you a simple refactor

**Comment by YT-Advanced** [comment]
> Instead, if you add me as a collaborator in your repo, I can give you a simple refactor

I have added you to my repos

**Pull request closed without merging**
