### PR TITLE
feat(YouTube/Searchbar): change cursor color dynamically

### PR DESCRIPTION
**Pull request by Francesco146**

### CODE REVIEW

**Comment by 0xrxL** [comment]
Posta un'immagine o un video della mod, così valuto se quest'ultima può andare ad arricchire il mio client personale.

👍

**Comment by Francesco146** [comment]
wtf - Italian mentioned 🇮🇹🍝

anyway, here's the screenshot:

<details>
  <summary>screenshots:</summary>
  
IMG_20240701_200349_205
IMG_20240701_200348_509

</details>

**Comment by 0xrxL** [comment]
> wtf - Italian mentioned 🇮🇹🍝
> 
> anyway, here's the screenshot:
> 
> screenshots:
> IMG_20240701_200349_205 IMG_20240701_200348_509

🇮🇹🤣

Good...anyway, if you're interested, I still have a mod to port to ReVanced (normal or extended).

Some videos have a shop section, that is shown in a dedicated panel, opened at the beginning of the video. This mod disables these annoying pop-up panels (which also appear on playlists and live videos...also if I don't know if inotia already added it on this repo 🤷‍♂️).

**Comment by inotia00** [comment]
Thanks

**Pull request merged**
