### PR TITLE
feat(YouTube): Add `Hide videos by duration` and `Hide videos by views count` greater than specified value

### PR DESCRIPTION
**Pull request by anddea**
https://github.com/inotia00/revanced-integrations/pull/37

Should I open one PR with multiple commits/features?

### CODE REVIEW

**Comment by inotia00** [comment]
To minimize commit confusion, this PR will be merged together when merging https://github.com/inotia00/revanced-patches/pull/47.

**Comment by anddea** [comment]
> To minimize commit confusion, this PR will be merged together when merging https://github.com/inotia00/revanced-patches/pull/47.

I can either add more commits to this PR and name them accordingly, and if you merge them normally with the default merge option, they will all be visible separately in the git history, or I can open other PRs for each feature and you can squash and merge them, which one do you prefer?

**Comment by inotia00** [comment]
It's okay to combine them all in one PR

**Comment by inotia00** [comment]
Thanks

**Pull request merged**
