### PR TITLE
fix(Disable Music playback speed): Fix side effect left

### PR DESCRIPTION
**Pull request by YT-Advanced**
In `WEB` and `MWEB` client, player response contains `microformat` JSONObject which provide us information about video category, such as `Music`, `Entertainment`, `Education`, etc. So we can use this useful field to check if a video is music or not.

Other changes:
- Do not override playback speed on livestream by default (Remove settings)
- Update client info

### CODE REVIEW

**Comment by inotia00** [comment]
As far as I know, when using `WEB` or `MWEB` clients, the server sometimes returns a response `Sign in to confirm you’re not a bot` and asks for a poToken: https://github.com/LuanRT/YouTube.js/issues/674

I will review the PR after it has been sufficiently tested

**Comment by YT-Advanced** [comment]
Ah got it. I think I should close this PRs. However, I will keep the branch in case u want to reopen it back xD

**Comment by inotia00** [comment]
If you use `MWEB` client and Safari User-Agent, this may be a valid PR

**Comment by YT-Advanced** [comment]
Yea I'm working on it

**Pull request closed without merging**
