### PR TITLE
feat(YouTube/Shorts overlay buttons) New outline icons for Shorts

### PR DESCRIPTION
**Pull request by anddea**
New outline icons for Shorts. I added them to Overlay Buttons patch and they are availbale if `Outline icons` patch selected.
You may seperate Shorts and Overlay buttons.

> [!WARNING]  
> It might be hard to see Outline buttons on white backgrounds, no matter how bold I make them or how much shadow I add to those icons.
> 
> Edit: Maybe I'll make new icons with the semi-transparent circle background later, like in YT Music. I'm open for other suggestions.

<details>
<summary>Screenshots</summary>
<br>
New - currently I'm commiting those icons <br>
Old - default icons <br>
Other - icons I may commit if community prefers them more (bolder, more shadow, but a little blocky) <br><br>

scr
</details>

### CODE REVIEW

**Comment by Francesco146** [comment]
404 screenshots not found

**Comment by anddea** [comment]
> 404 screenshots not found

Fixed it

**Comment by inotia00** [comment]
During the process of merging and testing commits, I found that the outline icon was not applied to old shorts
(Patch YouTube v18.25.40 ~ v18.33.40, or spoof the app version to v18.33.40 or earlier)

Old_Shorts

The versions currently supported by rvx patches are YouTube v18.25.40 to v18.41.39, so the outline icon should work as intended from YouTube v18.25.40 to v18.33.40 as well

Since the outline icon for old shorts was not added, I will revert the commit

Please reopen PR after this issue is resolved

**Comment by sams452m** [comment]
You don't need to add shadow to the shorts outline icons just make them bold and add a grey overlay with low opacity to the shorts player so when the user plays the video if it has white color it doesn't conflict with the shorts buttons

**Comment by sams452m** [comment]
> > 404 screenshots not found
> 
> Fixed it



> New outline icons for Shorts. I added them to Overlay Buttons patch and they are availbale if `Outline icons` patch selected. You may seperate Shorts and Overlay buttons.
> 
> Warning It might be hard to see Outline buttons on white backgrounds, no matter how bold I make them or how much shadow I add to those icons.
> 
> Edit: Maybe I'll make new icons with the semi-transparent circle background later, like in YT Music. I'm open for other suggestions.
> 
> Screenshots

You don't need to add shadow to the shorts outline icons just make them bold and add a grey overlay with low opacity to the shorts player so when the user plays the video if it has white color it doesn't conflict with the shorts buttons

**Comment by anddea** [comment]
> You don't need to add shadow to the shorts outline icons just make them bold and add a grey overlay with low opacity to the shorts player so when the user plays the video if it has white color it doesn't conflict with the shorts buttons

I'll try to add edge darkening, like header icons (search, camera, menu) and bottom description, if I can figure out how

**Pull request merged**
