### PR TITLE
Close #1529

### LINKED ISSUE #1529: suggestion(YouTube): add dots in strings where they needed
### Application

YouTube

### Description

Strings in YTM grammatically looks right, they have dot at the end, but in YT you didn't do that, please add . where they needed

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

### PR DESCRIPTION
**Pull request by girshcatt**
Now i am finally done with damn dots, also i added : in revanced_import_settings_inform and removed second space in revanced_ryd_attribution_summary. You can close https://github.com/inotia00/ReVanced_Extended/issues/1529

### CODE REVIEW

**Comment by girshcatt** [comment]
One little question about dot remains, it about three strings:
revanced_save_playback_speed
revanced_save_video_quality_mobile
revanced_save_video_quality_wifi
Can i add dots in end of them, i ask because I doubt that after this these toasts will work incorrect, because they has nothing after : 
If all will work right can you add dots to these strings? Also in YTM

**Comment by girshcatt** [comment]
Is "revanced_ryd_video_likes_hidden_by_video_owner">Hidden string a toast? Please attach screenshot

**Comment by inotia00** [comment]
Probably right

I'm not sure because that string was added by the ReVanced Team

**Comment by girshcatt** [comment]
Please add dot in the end of sb_vote_failed_timeout string

**Comment by girshcatt** [comment]
> Probably right
> 
> I'm not sure because that string was added by the ReVanced Team

https://github.com/ReVanced/revanced-integrations/blob/dd045ad985f8289cc11381d31adfb264f0f278dd/app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java#L213-L224

We shouldn't change it, it is not a toast, check link from the code

**Pull request merged**
