### PR TITLE
feat(youtube/force-video-codec): Force `HDR Codec` patch

### PR DESCRIPTION
**Pull request by YT-Advanced**
Integrations changes: https://github.com/inotia00/revanced-integrations/pull/24

### CODE REVIEW

**Comment by anispwyn** [comment]
LGTM
from 
sidekick_FlD83LS3qN

**Comment by YT-Advanced** [comment]
@HoriKyoukosimp Oh my god, spammer 🫠

**Comment by anispwyn** [comment]
wdym spammer smh

**Comment by YT-Advanced** [comment]
> wdym spammer smh

I mean your Github bio :)))

**Comment by anispwyn** [comment]
real

**Pull request merged**
