### PR TITLE
feat(YouTube/Custom branding icon): add patch option `YouTube (Minimal header)`

### PR DESCRIPTION
**Pull request by MondayNitro**
similar to playstore icon introduced a while back
dsjds

it looks particularly good with the wide search bar enabled since the search bar can now occupy the entire space while also showing yt logo
Screenshot_2024-09-21-12-21-36-716_app revanced android youtube
 
premium text will continue to appear whe enabled premium header, the regular header will be textless

### CODE REVIEW

**Comment by MondayNitro** [comment]
can someone tell me whats this vector `settings/drawable/revanced_extended_settings_key_icon.xml` i simply copied from youtube folder, i patch with stock youtube branding but cant find this file anywhere inside apk

**Comment by GucekPL** [comment]
Suppose I will make my own custom branding. As a non-premium icon I would give your minimal icon, and for the premium logo I would add logo with ReVanced in name. Would the client enforce this, including the wide search bar margin?

**Comment by inotia00** [comment]
The PR adds the change to the `Custom branding icon for YouTube` patch, but does not change the icon in the launcher

Also, it does not change the premium header

If proper description is not added, it can be confusing for users

Let's assume the following situation:
1. The user included the `Custom branding icon for YouTube` patch (with patch options set to `Minimal`)
2. The user excluded the `Toolbar components` patch
3. Since the user excluded the `Toolbar components` patch, the premium header will always be used if the user is a YouTube Premium subscriber (There is no way to switch to the minimal header)

All patches should work independently, but this PR does not
(If the user is a YouTube Premium subscriber, they must include the `Toolbar components` patch)

For this reason, it seems more appropriate to add it to the `Custom header for YouTube` patch

**Comment by GucekPL** [comment]
Sorry, I meant custom header, and on I wrote branding 😅

**Comment by MondayNitro** [comment]
minimal icon has yt icon so launcher icon doesnt need to be changed

**Comment by MondayNitro** [comment]
> All patches should work independently, but this PR does not (If the user is a YouTube Premium subscriber, they must include the `Toolbar components` patch)

youre right, i think i should keep premium wordmark minimal too, users who want premium text shouldnt have to do with minimal option selection

**Comment by inotia00** [comment]
The current changes are not that bad

Since the name of the patch option still does not include that it only changes the header, I will change the name of the patch option once more:

1. Change the name of the patch option from `YT Minimal` to `YouTube (Minimal header)`.
2. Move the patch option `YouTube (Minimal header)` below the patch option `YouTube`
3. This makes it a bit clearer that this only changes the header, since the patch option `YouTube (Minimal header)` is located directly below the patch option `YouTube`

**Comment by inotia00** [comment]
Thanks

**Comment by ghost** [comment]
@MondayNitro @inotia00 

Theres a problem with this minimal icon though, the youtube icon sits too close to the search bar:

369602346-bb2aabad-05f4-4137-8868-f90d3db8cbf5

When compared to the regular icon:

Screenshot_20240927_163541_RVX

Minimal youtube icon should have similar empty space in between the search bar and the icon.

**Comment by inotia00** [comment]
I approved this PR, but upon second thought, I think it's not appropriate to include the file for YouTube's branding logo in the patch

Because it could be a valid reason for a DMCA takedown of the repository

I will revert this PR in the next release

**Comment by Francesco146** [comment]
the Custom Branding patch still allows everyone to apply this header from this PR. just so anyone's wondering, there's no disadvantage by reverting these changes

**Pull request merged**
