### PR TITLE
feat(microg): add microg-mmt-icon and microg-materialyou patches

### PR DESCRIPTION
**Pull request by ayushTNM**
- feat(microg): add `custom-branding-microg-mmt` patch
- feat(microg): add `microg-materialyou` patch

materialyou patch needs `com.google.android.material` library, which is included in my mMicroG repo:
https://github.com/ayushTNM/mMicroG

Or you could adjust it to take into account if `com.google.android.material` library is included

### CODE REVIEW

**Comment by inotia00** [comment]
The following files are automatically generated by the build script
- README.md
- gradle.properties
- patches.json

Please roll back these three files

**Comment by ayushTNM** [comment]
Done

**Comment by kazimmt** [comment]
> Done

What is the reason of changing `revanced_prefs.xml`

**Comment by inotia00** [comment]
I will edit it manually after the merge
Thanks anyway

**Pull request merged**
